#!/bin/bash
# Environment Variable Loader Script
# Generated by Claude Code - August 19, 2025
# 
# Usage: source ./load-env.sh
# This script loads all project environment variables

echo "🔧 Loading DirectDrive Authority Engine environment variables..."

# Load main environment file
if [ -f ".env.local" ]; then
    set -a  # Enable auto-export
    source .env.local
    set +a  # Disable auto-export
    echo "✅ Loaded .env.local"
else
    echo "❌ .env.local not found!"
    exit 1
fi

# Load n8n specific environment if exists
if [ -f ".env.n8n" ]; then
    set -a
    source .env.n8n
    set +a
    echo "✅ Loaded .env.n8n"
fi

# Verify critical services
echo ""
echo "🔍 Verifying connections..."

# Check Supabase
if [ ! -z "$NEXT_PUBLIC_SUPABASE_URL" ]; then
    echo "✅ Supabase: $NEXT_PUBLIC_SUPABASE_URL"
else
    echo "❌ Supabase URL not set"
fi

# Check n8n
if [ ! -z "$N8N_BASE_URL" ]; then
    echo "✅ n8n: $N8N_BASE_URL"
else
    echo "❌ n8n URL not set"
fi

# Check Database
if [ ! -z "$DB_HOST" ]; then
    echo "✅ Database: $DB_HOST"
else
    echo "❌ Database host not set"
fi

echo ""
echo "🚀 Environment loaded successfully!"
echo "💡 All credentials are now available in your session."